-- Run BEFORE 02-import.sql.
--
-- 1. None of the 255 proposed (name, village) pairs may already exist. Expect 0.
select count(*) as must_be_0 from venues v
where (v.name, coalesce(v.village,'')) in (
  ('The Bell Inn', 'Balsham'),
  ('The Bull', 'Burrough Green'),
  ('The Greyhound', 'Chevington'),
  ('The King''s Head', 'Pebmarsh'),
  ('The Swan', 'Lavenham'),
  ('The Street', 'Capel St. Mary'),
  ('Meet Mike', 'Norwich'),
  ('Lingwood England Football', 'Lingwood'),
  ('Fordham British Legion', 'Fordham'),
  ('Fardons at The Swan', 'The Swan'),
  ('Welwyn Garden City Town Centre Street Food Heroes', 'Welwyn Garden City'),
  ('BAR HILL', 'CAMBRIDGE'),
  ('The Jerk Chicken Man', 'Hertford'),
  ('Hop Fields', 'Saffron Walden'),
  ('Crumble King of Northstowe', 'Northstowe'),
  ('Letchworth store', 'Letchworth'),
  ('Banbury Show', 'Banbury'),
  ('Jesus Green', 'Cambridge'),
  ('Rainbow Rocket', 'Cambridge'),
  ('Smile Jamaica', 'NEWMARKET'),
  ('EAT Street MK', 'Milton Keynes'),
  ('Street Food Heroes', 'Ashwell'),
  ('Poss leave', 'Norfolk'),
  ('TBC Black Dog Music Project', 'Norwich'),
  ('Gosfield Village Fete', 'Gosfield'),
  ('Bures Music Festival', 'Bures'),
  ('Kings Forest Car Park', 'Bury Saint Edmunds'),
  ('48 Clifton Road', 'Cambridge'),
  ('Newton Flotman Social club', 'Newton Flotman'),
  ('Trowse village fete', 'Trowse'),
  ('Father''s Day', 'Haverhill'),
  ('The Live Lounge', 'Stowmarket'),
  ('The Lounge', 'Stowmarket'),
  ('Fairfield park', 'Stotfold'),
  ('Sawasdee Melford, Nethergate Brewery & Distillery', 'Nethergate Brewery & Distillery'),
  ('The Brickmakers', 'Norwich'),
  ('Prep for Armour fest', 'Ludham'),
  ('The Shannon Inn', 'Bucklesham'),
  ('Felixstowe Carnival', 'Felixstowe'),
  ('BTYFC Baldock Town Youth', 'Baldock'),
  ('Armourfest 26', 'Forncett St Peter'),
  ('The White Hart', 'Campton'),
  ('Fen Edge Festival', 'Cottenham'),
  ('Trinity College', 'Cambridge'),
  ('King''s Affair', 'Cambridge'),
  ('Stapleford Feast', 'Stapleford'),
  ('Hi Park Primary Summer Fair', 'Cambridge'),
  ('Black Horse Rampton', 'Rampton'),
  ('Histon and Impington Recreation Ground', 'Histon and Impington'),
  ('Wootton Community Centre', 'Wootton'),
  ('Biggleswade Market', 'Biggleswade'),
  ('Tyres', 'Lingwood'),
  ('Southery Village Hall', 'Southery'),
  ('Shuttleworth Festival of flight', 'Shuttleworth'),
  ('Village Hall and playing field', 'Newton Flotman'),
  ('The Norfolk Tank Museum', 'Forncett St Peter'),
  ('Little Thetford - Open Group', 'Little Thetford'),
  ('Marham Park', 'Felixstowe'),
  ('Belchamp Community House', 'Belchamp'),
  ('Relay for Life', 'Bury St Edmunds'),
  ('Rougham Estate Pumpkin Patch', 'Rougham'),
  ('Milton Country Park', 'Milton'),
  ('Marky D''s', 'Norfolk'),
  ('Todd In The Hole Festival', 'Todd In The Hole Festival'),
  ('Chilfest', 'Chilfest'),
  ('Northstowe Town', 'Northstowe'),
  ('Zaket Potato', 'Norwich'),
  ('King''s College Chapel', 'Cambridge'),
  ('PIE Performance Porsche', 'Ipswich'),
  ('THE MANGER', 'Bradfield Combust'),
  ('Bailey Hills Vineyard', 'Wickham Hall'),
  ('Ampthill Big Tent Weekend', 'Ampthill'),
  ('Rushden Party in The Park', 'Rushden'),
  ('St John''s College', 'Cambridge'),
  ('Inclecboro Fields Campsite', 'West Runton'),
  ('Hadleigh high street', 'Hadleigh'),
  ('Unit 8A, The Grip Industrial Estate', 'Linton'),
  ('Culford Classic Car Show', 'Culford'),
  ('Dog Day Fairhaven', 'Unknown'),
  ('Helmingham Gardens', 'Helmingham Estate'),
  ('8.55 appointment @ dr', 'Unknown'),
  ('No RWE', 'Unknown'),
  ('Ranworth beer festival', 'Unknown'),
  ('Ashdon Village Hall Car Park', 'Ashdon'),
  ('Cancer Research UK Cambridge Institute', 'Cambridge'),
  ('Audley End Enchanted Railway', 'Audley End'),
  ('White Hart Pub', 'Attleborough'),
  ('FY Camp', 'Wendling'),
  ('dr appointment', 'Great Yarmouth'),
  ('Incleboro Fields Caravan and Motorhome Club Campsite', 'West Runton'),
  ('Estuary Park', 'Melford'),
  ('Rookswood club', 'March'),
  ('Audley End Miniature Railway', 'Audley End'),
  ('Puckeridge Pony Club', 'Brent Pelham'),
  ('Corporate Lunch', 'Haverhill'),
  ('West Suffolk Classic Show', 'Haverhill'),
  ('RHS Sandringham Flower Show', 'Sandringham'),
  ('Sandringham Estate', 'Sandringham'),
  ('Churro Boyz', 'Letchworth'),
  ('Royal Air Force Day Event 2026', 'Ipswich'),
  ('Down By The River', 'BURY ST EDMUNDS'),
  ('BigDaySmallCountry Festival', 'Nayland'),
  ('Mid-Suffolk Light Railway', 'Mid-Suffolk'),
  ('The Framsden Greyhound', 'Framsden'),
  ('Great Blakenham Village Hall', 'Great Blakenham'),
  ('Worlingworth Community Centre', 'Woodbridge'),
  ('Jive Swing Festival', 'Watford'),
  ('Transit Mot due', 'Cromer'),
  ('46 Chesterton Rd', 'Cambridge'),
  ('135-163 Galton Rd', 'Cambridge'),
  ('Brookside', 'Dalham'),
  ('Unit 2, Convent Drive', 'Waterbeach'),
  ('Gentleman Jacks', 'Acle'),
  ('Norfolk Broads Caravan and Motorhome Club Campsite', 'Ludham'),
  ('River Nights Event', 'Audley End'),
  ('Connaught Hall', 'Norwich'),
  ('music on the green', 'long melford'),
  ('Rendlesham Campsite', 'Rendlesham'),
  ('AFRICA ALIVE', 'Norwich'),
  ('Cantly Fun Day', 'Cantley'),
  ('Salen', 'Salen'),
  ('Mezzoforte', 'Cambridge'),
  ('Lord Nelson', 'Norfolk'),
  ('Armour fest', 'Norwich'),
  ('Beetle Juice Event', 'Jimmy Farm'),
  ('Cambourne Cricket Pavilion', 'Cambourne'),
  ('Little Thetford Village Hall', 'Little Thetford'),
  ('Great Waldingfield', 'Great Waldingfield'),
  ('Body Funk', 'Cambridge'),
  ('Dog show', 'Norfolk'),
  ('Sudbury Street Food Festival', 'Sudbury'),
  ('Frog''s Farm', 'Sundowner'),
  ('Westerfield Horse Show', 'Westerfield'),
  ('Hylands Park', 'Chelmsford'),
  ('Biomedical Campus Cambridge', 'Cambridge'),
  ('Bristol International Balloon Fiesta', 'Bristol'),
  ('Hylands Estate', 'Chelmsford'),
  ('Dunstable', 'Dunstable'),
  ('Playbox', 'Cambridge'),
  ('St Neots', 'St Neots'),
  ('The Orchard Gardens', 'Thetford'),
  ('Co ob Barking rd', 'Needham Market'),
  ('The Bell Bar', 'Buxhall'),
  ('Lannock Farm', 'Hitchin'),
  ('Wootton Food and music festival', 'Wootton'),
  ('The Green Barn Farm Shop', 'Cambridge'),
  ('Hitchin Food Festival', 'Hitchin'),
  ('Moreton Hall Community Centre', 'Bury St Edmunds'),
  ('Ridgewell Village Hall', 'Ridgewell'),
  ('The Royal British Legion, Fordham', 'Fordham'),
  ('Bury Food & Drink Festival', 'Bury'),
  ('Brecks Vineyard', 'Hockwold cum Wilton'),
  ('University of Suffolk', 'Ipswich'),
  ('The Great Feast', 'Euston Hall'),
  ('Christening', 'Thetford'),
  ('Bennington Chilli Festival', 'Bennington'),
  ('Ashwell Show', 'Ashwell'),
  ('The White Swan', 'Bluntisham'),
  ('Elmsfest', 'Elmswell'),
  ('IVO Brewery', 'St. Ives'),
  ('Cock Inn', 'Werrington'),
  ('freethorpe village hall', 'Freethorpe'),
  ('Newton Flotman Quiz Night', 'Unknown'),
  ('BNatural Music Festival', 'BNatural'),
  ('foodPark Biomedical Campus', 'Langley'),
  ('Big Olney Food Festival', 'Olney'),
  ('alumasc water management', 'halstead'),
  ('east bergholt village summer fair', 'East Bergholt'),
  ('Suffolk Aviation Heritage Group', 'Great Cornard'),
  ('Steak & Honour', 'Cambridge'),
  ('CB1 Station Road', 'Cambridge'),
  ('Charity Music Festival', 'Hertford Heath'),
  ('Brandon', 'Brandon'),
  ('Holbrook', 'Holbrook'),
  ('Hilton Feast', 'Hilton'),
  ('Culford School', 'Bury St. Edmunds'),
  ('Rushbanks Farm Caravan and Camping Site', 'Bures'),
  ('West Bergholt Cricket Club Juniors', 'West Bergholt'),
  ('The Ship', 'Great Yarmouth'),
  ('The Gog', 'Cambridge'),
  ('The Cake Shed', 'Great Waldingfield'),
  ('Eddington, North West Cambridge Development', 'Cambridge'),
  ('Electric Paradise', 'Letchworth'),
  ('Chalkstone Fun Day', 'Haverhill'),
  ('Shudy Rocks', 'Shudy Camps'),
  ('Reggae Land', 'Letchworth'),
  ('Lochbuie', 'Lochbuie'),
  ('Bunessan Show', 'Bunessan'),
  ('Old Goat Brewery', 'Stansfield'),
  ('The Half Moon 1746', 'Felixstowe'),
  ('Camlife,Fulbourn', 'Fulbourn'),
  ('Higher Life', 'BURY ST EDMUND’S'),
  ('Physio', 'Unknown'),
  ('10 Dereham Road', 'Norwich'),
  ('Daisy’s Milk Shed', 'Cambridge'),
  ('Ipswich Town FC Fanzone', 'Ipswich'),
  ('Drina Bakes', 'Sudbury'),
  ('The Black Horse', 'Brent Pelham'),
  ('Halo Car Park', 'Stowmarket'),
  ('@Fashionthriftsociety', 'Peck''nam'),
  ('Crafty Bear Sip N Paint', 'Witham High Street'),
  ('The Village Club Farcet', 'Farcet'),
  ('Ramsey Neighbourhoods Trust', 'Ramsey'),
  ('Ely Fest', 'Ely'),
  ('George Iv', 'Sawbridgeworth'),
  ('Naama African Kitchen', 'Edwardstone White Horse'),
  ('Authentic Turkish Kebabs', 'Edwardstone White Horse'),
  ('Noodles, Bao Buns, Curries', 'Edwardstone White Horse'),
  ('Suffolk Spice Fusion Curries And Naan Wraps', 'Edwardstone White Horse'),
  ('Authentic Thai Food', 'Edwardstone White Horse'),
  ('Jerk Chicken Loaded Fries', 'Edwardstone White Horse'),
  ('School Event', 'Milton Keynes'),
  ('Corporate Party For @Uk Power Network', 'Stratford'),
  ('Unit 21 Wolseley Business Park', 'Oulton Broad'),
  ('Zaket Trailer', 'Norwich'),
  ('Ely Arts Festival', 'Ely'),
  ('Felixstowe (Opposite Car Shop & Library)', 'Felixstowe'),
  ('Milton Foot Golf @Kinnerz Coaching', 'Milton'),
  ('West End Fete', 'Surrey'),
  ('Highfield Academy Summer Fete', 'Ely'),
  ('Hadleigh Lay By At Beestons', 'Beestons'),
  ('Belstead Arms, Ipswich Ip2 9qu', 'Ipswich'),
  ('Festival Silver Street', 'Godmanchester'),
  ('Festival Barford Road', 'Blunham'),
  ('Soham Prom, Soham Village College', 'Soham'),
  ('Chatteris Midsummer Festival', 'Chatteris'),
  ('Dereham Town Football Club', 'Dereham'),
  ('Junior School', 'White Woman Lane'),
  ('North Motherwell', 'Motherwell'),
  ('Old Forgewood & Forgewood', 'Forgewood'),
  ('Ascensos Motherwell (Car Park)', 'Motherwell'),
  ('Craigneuk (Behind Farmfoods)', 'Craigneuk'),
  ('Muirhouse (Beside Uppercrust)', 'Muirhouse'),
  ('Torrence Park (Panton Ave)', 'Torrence Park'),
  ('Cambridge Botanic Garden', 'Cambridge'),
  ('Krazy Horse Late Nights', 'Bury St Edmunds'),
  ('Nene Park, Peterborough- Nene Park Trust', 'Peterborough'),
  ('Gala Day Godmanchester', 'Godmanchester'),
  ('Picnic In The Park Godmanchester', 'Godmanchester'),
  ('Long Road College Open Evening', 'Cambridge'),
  ('West Hub Summer Party', 'Cambridge'),
  ('Stowmarket Food & Drinks Festival', 'Stowmarket'),
  ('Clare- Platform 1', 'Clare'),
  ('Stowmarket Food Festival', 'Stowmarket'),
  ('Isleham Gala', 'Isleham'),
  ('Shefford Market', 'Shefford'),
  ('Felixstowe Charity Event', 'Felixstowe'),
  ('The Waggon & Horses', 'Milton'),
  ('Transit Mot', 'Unknown'),
  ('Haircut', 'Unknown'),
  ('G’s Family Day', 'G''s Family Day'),
  ('Dionne visit', 'Unknown'),
  ('California Social Club', 'California'),
  ('Little Wings Of Hope Event', 'Essex'),
  ('Hare And Hounds', 'East Bergholt')
);

-- 2. Context, not a gate: 43 venues carry a NULL village today. They are pre-existing and this pack
--    does not touch them. Every row this pack inserts HAS a village — a null village can never
--    conflict in a unique index (nulls are DISTINCT), so it would duplicate for ever. Manual §5.3.
select count(*) as venues_with_null_village_today from venues where village is null;   -- expect 43

-- 3. The snapshot from 00-snapshot.sql should still match the live table.
select (select count(*) from venues) as live, (select count(*) from venues_backup_20260909) as backup;   -- expect 559, 559
