-- 143 terms from the Sheet's Exclusions tab, read live 8 September 2026.
-- term_key = normalizeName(term), the value run-scraper.js:860 actually compares.
-- hits_truck is set on the 5 terms that fuzzy-match a REAL Trucks-tab name under the
-- SCRAPER's 1-edit Levenshtein (run-scraper.js:66-92) — the matcher the scraper uses.
-- ⚠️ Under the APPS SCRIPT's containment matcher (v6.57:1240-1245) 9 terms hit 7 trucks; the extra
--    four are recorded in 04-containment-extra.sql. They are NOT flagged here because the flag
--    describes what the SCRAPER will do with the term.
insert into discovery_exclusion_terms (term, term_key, source, hits_truck, created_by) values
  ('TBC', 'tbc', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('Pizza & Boards', 'pizzaboard', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('Ram Inn Karaoke', 'raminnkaraoke', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('Stapleford Granary - outdoor concert', 'staplefordgranaryoutdoorconcert', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('live music', 'livemusic', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('Busy', 'busy', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('quiz nights', 'quiznight', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('AXLE + HOP', 'axlehop', 'sheet-import-2026-09', 'Axle & Hop', 'migration-step-2'),
  ('Dancing In The Sand (feat. Vinnie Caggiano)', 'dancinginsandfeatvinniecaggiano', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('The Dog Inn Quiz', 'doginnquiz', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('outdoor concert', 'outdoorconcert', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('Private Party', 'privateparty', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('Brickmakers Slayfest 2026', 'brickmakerslayfest2026', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('Ipswich Town F.C. customers', 'ipswichtownfccustomer', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('Bartlow Three Counties Charity Walk', 'bartlowthreecountiecharitywalk', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('great music and celebration', 'greatmusiccelebration', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('Birthday celebrations with Crossing 55', 'birthdaycelebrationwithcrossing55', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('family fun', 'familyfun', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('karaoke', 'karaoke', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('You Got the Love', 'yougotlove', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('WINTRINGHAM COMMUNITY DAY', 'wintringhamcommunityday', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('Victor & Company', 'victor', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('Lindsell Summer Fayre', 'lindsellsummerfayre', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('END OF SEASON AWARDS & RACE NIGHT', 'endofseasonawardracenight', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('Wroxham Barns', 'wroxhambarn', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('Music at the nest', 'musicatnest', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('Hadleigh Show', 'hadleighshow', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('The 187th Hadleigh Show', '187thhadleighshow', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('MDP-GAC-UEFJ', 'mdpgacuefj', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('Parish Council meeting', 'parishcouncilmeeting', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('SUN OUT = JAMAICAN FOOD', 'sunoutjamaican', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('Humdinger', 'humdinger', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('Azahar Spanish Food', 'azaharspanish', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('Not working Humdinger', 'notworkinghumdinger', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('NO FOOD TRUCK', 'notruck', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('car show', 'carshow', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('Lingwood England Football', 'lingwoodenglandfootball', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('Private Event', 'privateevent', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('Workington Beer Festival', 'workingtonbeerfestival', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('Milton Colts FC Presentation Day', 'miltoncoltfcpresentationday', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('ALCONBURY FOOD FESTIVAL', 'alconburyfestival', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('Lingwood Village Hall Karaoke', 'lingwoodvillagehallkaraoke', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('live DJ', 'livedj', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('music', 'music', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('Sudbury Market', 'sudburymarket', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('Witchford Colts Presentation Day', 'witchfordcoltpresentationday', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('RAF Lakenheath', 'raflakenheath', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('MUSIC and ENTERTAINMENT!', 'musicentertainment', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('NO TRUCK THIS WEEK', 'notruckthiweek', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('TBC Black Dog Music Project', 'tbcblackdogmusicproject', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('beer festivals', 'beerfestival', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('South Lee', 'southlee', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('Diss', 'dis', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('Bures Music Festival', 'buremusicfestival', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('Cambridge uni may Balls', 'cambridgeunimayball', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('Wootton Food & Music Festival', 'woottonmusicfestival', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('Off The Beaten Truck', 'offbeatentruck', 'sheet-import-2026-09', 'Off The Beaten Truck', 'migration-step-2'),
  ('Newmarket Charity Cricket Match', 'newmarketcharitycricketmatch', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('Pork Stew of the week', 'porkstewofweek', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('Bertram Blacks Burgers', 'bertramblackburger', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('Armourfest 26', 'armourfest26', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('wedding', 'wedding', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('No Pizzas as he has a gun !', 'nopizzaahehaagun', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('Trowse village fete', 'trowsevillagefete', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('We Are Wintringham', 'wearewintringham', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('DJ Creem', 'djcreem', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('Page · Food Truck', 'pagetruck', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('Kool & The Gang', 'koolgang', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('Jungle Jazz', 'junglejazz', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('OFF THE BEATEN TRUCK SUMMER PARTY', 'offbeatentrucksummerparty', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('The Vine', 'vine', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('football', 'football', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('Dessert MK', 'dessertmk', 'sheet-import-2026-09', 'Dessert MK', 'migration-step-2'),
  ('cars and coffee event', 'carcoffeeevent', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('Gas delivery', 'gadelivery', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('Disco Shed with the Freewheeler DJ’s spinning all the tunes', 'discoshedwithfreewheelerdjspinningalltune', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('SUMMER PARTY', 'summerparty', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('PIE Performance Porsche', 'pieperformanceporsche', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('JBM Music & Events', 'jbmmusicevent', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('classic car show', 'classiccarshow', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('Disco Shed with the Freewheeler DJ’s', 'discoshedwithfreewheelerdj', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('SAFFRON WALDEN SUMMER PARTY', 'saffronwaldensummerparty', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('Closed Today', 'closedtoday', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('Afro Sound Machine', 'afrosoundmachine', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('Jerk & Braai Cafe', 'jerkbraaicafe', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('No RWE', 'norwe', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('Ranworth beer festival', 'ranworthbeerfestival', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('Private Function White Hart Pub', 'privatefunctionwhitehartpub', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('Supporting Small Business: An Update on Our Journey', 'supportingsmallbusinesanupdateonourjourney', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('corporate lunch', 'corporatelunch', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('There will be no food trucks on Saffron Walden Common on Thursday 16 July.', 'therewillbenotruckonsaffronwaldencommononthursday16july', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('Cake Shed', 'cakeshed', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('Page', 'page', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('Plain Scones to takeaway', 'plainsconetotakeaway', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('Monday munchies', 'mondaymunchie', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('POP-UP STREET FOOD PARTY', 'popupparty', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('Holbrook', 'holbrook', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('No Pizza Van', 'nopizzavan', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('Prep for Armour fest', 'prepforarmourfest', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('Royal Air Force Day Event 2026', 'royalairforcedayevent2026', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('THE SUNDAY ROAST BURGER', 'sundayroastburger', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('Private function FY Camp', 'privatefunctionfycamp', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('Electric Paradise', 'electricparadise', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('Keep your eyes on England, not the hob. ⚽🔥 Have', 'keepyoureyeonenglandnothobhave', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('Annual Beer Festival of The Angel Inn Larling', 'annualbeerfestivalofangelinnlarling', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('TACO TUESDAY', 'tacotuesday', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('THE FLYING DUTCHMAN', 'flyingdutchman', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('River Nights - Country & Western', 'rivernightcountrywestern', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('Haircut', 'haircut', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('8.55 appointment @ dr', '855appointmentdr', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('wedding catering', 'weddingcatering', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('Evenings in the Park', 'eveninginpark', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('Vinyl Mixes', 'vinylmixe', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('Summer Fete', 'summerfete', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('Newmarket Sausage Festival', 'newmarketsausagefestival', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('90th birthday celebration', '90thbirthdaycelebration', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('JUST BAKED BY SOPHIE', 'justbakedbysophie', 'sheet-import-2026-09', 'Just Baked by Sophie', 'migration-step-2'),
  ('SURF ‘N’ TURF', 'surfnturf', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('Rougham Estate Pumpkin Patch', 'roughamestatepumpkinpatch', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('Bristol International Balloon Fiesta', 'bristolinternationalballoonfiesta', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('G’s Family Day', 'gfamilyday', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('WINGS WEDNESDAY', 'wingwednesday', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('Mega Munch boxes', 'megamunchboxe', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('Queen''s Head', 'queenhead', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('kids fun day', 'kidfunday', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('SALEN SHOW 2026', 'salenshow2026', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('The Linton Kitchen', 'lintonkitchen', 'sheet-import-2026-09', 'The Linton Kitchen', 'migration-step-2'),
  ('TRAINING DAY AT HOME', 'trainingdayathome', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('family funeral', 'familyfuneral', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('Dog show', 'dogshow', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('music festival', 'musicfestival', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('RUNNING FESTIVAL', 'runningfestival', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('IVY & BOND Tea Cosy & Coffee', 'ivybondteacosycoffee', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('Transit Mot due', 'transitmotdue', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('NEW WORLD WINE', 'newworldwine', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('NO OTBT FOOD TRUCKS', 'nootbttruck', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('Skatejam', 'skatejam', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('Newton Flotman Quiz Night', 'newtonflotmanquiznight', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('Goat Fest', 'goatfest', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('Dolly Parton', 'dollyparton', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('Bad Company', 'bad', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('The White Stripes', 'whitestripe', 'sheet-import-2026-09', null, 'migration-step-2'),
  ('BNatural Music Festival', 'bnaturalmusicfestival', 'sheet-import-2026-09', null, 'migration-step-2')
on conflict (term_key) do nothing;

-- Expect 143.
select count(*) as imported from discovery_exclusion_terms;
