import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@supabase/supabase-js'
import { createSupabaseServerClient } from '@/lib/supabase/server'

const supabase = createClient(
  process.env.SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
)

export async function POST(req: NextRequest) {
  const supabaseAuth = await createSupabaseServerClient()
  const { data: { user } } = await supabaseAuth.auth.getUser()
  if (!user) return NextResponse.json({ error: 'Unauthorised' }, { status: 401 })

  const { newEmail } = await req.json()
  if (!newEmail?.trim()) return NextResponse.json({ error: 'Email required' }, { status: 400 })

  const normalised = newEmail.trim().toLowerCase()

  const { data: operator } = await supabase
    .from('operators')
    .select('id, email')
    .eq('auth_user_id', user.id)
    .single()

  if (!operator) return NextResponse.json({ error: 'Operator not found' }, { status: 404 })

  if (normalised === operator.email?.toLowerCase()) {
    return NextResponse.json({ error: 'That is already your current email' }, { status: 400 })
  }

  // Check not already in use across both tables
  const [{ data: existingOperator }, { data: existingStaff }] = await Promise.all([
    supabase.from('operators').select('id').eq('email', normalised).maybeSingle(),
    supabase.from('truck_users').select('id').eq('email', normalised).maybeSingle(),
  ])

  if (existingOperator || existingStaff) {
    return NextResponse.json({ error: 'This email is already registered on HatchGrab' }, { status: 400 })
  }

  // Insert change request — token generated by DB default
  const { data: change, error: insertError } = await supabase
    .from('operator_email_changes')
    .insert({
      operator_id: operator.id,
      old_email: operator.email,
      new_email: normalised,
    })
    .select('id, token')
    .single()

  if (insertError || !change) {
    return NextResponse.json({ error: 'Failed to create change request' }, { status: 500 })
  }

  const verifyUrl = `${process.env.NEXT_PUBLIC_HATCHGRAB_URL}/verify-email?token=${change.token}`

  const brevoRes = await fetch('https://api.brevo.com/v3/smtp/email', {
    method: 'POST',
    headers: {
      accept: 'application/json',
      'api-key': process.env.BREVO_API_KEY!,
      'content-type': 'application/json',
    },
    body: JSON.stringify({
      sender: { name: 'HatchGrab', email: process.env.NEXT_PUBLIC_SUPPORT_EMAIL ?? 'hello@villagefoodie.co.uk' },
      to: [{ email: normalised }],
      subject: 'Verify your new HatchGrab email address',
      htmlContent: `
        <div style="font-family:Arial,sans-serif;color:#334155;max-width:600px;">
          <h2 style="color:#0f172a;">Verify your email address</h2>
          <p>You requested to change your HatchGrab email address to this address.</p>
          <p>Click the button below to verify. This link expires in 24 hours.</p>
          <p style="margin:32px 0;">
            <a href="${verifyUrl}"
               style="background:#ea580c;color:white;padding:14px 28px;
                      text-decoration:none;border-radius:8px;font-weight:bold;
                      display:inline-block;">
              Verify email address
            </a>
          </p>
          <p style="color:#64748b;font-size:13px;">
            If you didn't request this change, you can safely ignore this email.
            Your current email address remains active.
          </p>
        </div>
      `,
    }),
  })

  if (!brevoRes.ok) {
    const brevoError = await brevoRes.text()
    console.error('[change-email] Brevo send failed:', brevoRes.status, brevoError)
    return NextResponse.json({ error: 'Failed to send verification email' }, { status: 500 })
  }

  return NextResponse.json({ ok: true, changeId: change.id })
}
