-- 20260928_outreach_messages.sql
-- One row per outreach EMAIL — sent by the app, sent by hand from Outlook and imported, or received.
--
-- ⛔ NOT APPLIED. Run by hand in the Supabase SQL editor. Idempotent (`if not exists`).
-- 🔴 AFTER APPLYING, RUN THE LAST LINE: `notify pgrst, 'reload schema';`
--    PostgREST caches the schema. Until it reloads every request against this table returns PGRST205
--    ("Could not find the table ... in the schema cache") even though the table exists — which reads as
--    "the migration failed". The statement is the last line of this file; running the file whole
--    includes it.
--
-- ── 🔴 WHY A TABLE AND NOT A COLUMN ON outreach_contacts ────────────────────────────────────────────
-- `outreach_contacts` is the LADDER: one row per rung, hand-datable, and §57's derived next step reads
-- it. An email is a different object with a different lifetime — it is attempted, may be uncertain, may
-- be retried, carries a Message-ID that threads the next one, and may exist with NO contact row at all
-- (a test send, or an inbound reply). Hanging those on the ladder would make the ladder lie.
--
-- ── 🔴 WHAT THE UNIQUE CONSTRAINTS ARE FOR ──────────────────────────────────────────────────────────
--   • `message_id` — the RFC5322 Message-ID. The import is re-runnable BECAUSE of this: a second walk of
--     the mailbox conflicts instead of duplicating. It is also how a sent copy is found in Sent.
--   • `idempotency_key` — one compose can never send twice. The send route inserts the row BEFORE it
--     contacts the SMTP server, so a double submit collides here rather than at the mail host.
begin;

create table if not exists public.outreach_messages (
  id uuid primary key default gen_random_uuid(),

  -- WHO. Cascade: a deleted prospect takes its correspondence with it.
  prospect_id uuid not null references public.outreach_prospects(id) on delete cascade,
  -- The ladder row this send produced, when it produced one. `set null`: deleting a mis-logged contact
  -- must not delete the evidence that an email was sent — that is exactly the row you would then need.
  contact_id uuid references public.outreach_contacts(id) on delete set null,

  direction text not null check (direction in ('outbound', 'inbound')),
  -- sending  → inserted, not yet handed to the server
  -- sent     → the server accepted it
  -- failed   → a DEFINITE refusal (connect, auth, or any 4xx/5xx reply). Safe to retry.
  -- uncertain→ data handed over, no reply. 🔴 NEVER retried automatically; a human checks Sent first.
  -- received → inbound
  status text not null check (status in ('sending', 'sent', 'failed', 'uncertain', 'received')),
  -- A test send to Dominic himself. Logs no contact and does not count against the daily cap.
  is_test boolean not null default false,
  -- system       → composed and sent by this app
  -- mailbox_import → found in the mailbox by the importer (Outlook-sent, or an inbound reply)
  source text not null check (source in ('system', 'mailbox_import')),

  -- THREADING. `message_id` is generated by the app before the send for a system message, and read from
  -- the header for an imported one. `references` is the chain, space-separated, as the header stores it.
  message_id text not null unique,
  in_reply_to text,
  "references" text,

  subject text,
  from_address text,
  to_address text,
  -- The message's own Date header, not when the row was written.
  message_date timestamptz,

  -- WHERE THE COPY IS. Filled for an imported message, and after a system send once the copy is located
  -- or appended. `uidvalidity` is stored because a uid means nothing without it.
  mailbox text,
  uid bigint,
  uidvalidity bigint,

  -- WHAT WAS SENT. System messages only — the exact bodies, so a later reply can quote this one without
  -- going back to the mailbox. An imported message stores none: its body stays in the mailbox.
  html_body text,
  text_body text,

  -- 🔴 HOW THE COPY GOT INTO Sent, WHICH IS NOT THE SAME QUESTION AS WHETHER IT IS THERE.
  --   server_filed → the mail host filed it itself (Namecheap does this for authenticated submissions)
  --   appended     → the app had to IMAP APPEND it
  --   absent       → it is not there, and the operator is told so on that message
  sent_copy text not null default 'absent' check (sent_copy in ('server_filed', 'appended', 'absent')),

  attempts integer not null default 0,
  -- SANITISED only — code + a capped message. Never a credential, never a full server dialogue.
  last_error text,
  -- One compose, one send. See the note at the top.
  idempotency_key text unique,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- The two reads the app makes constantly: "this prospect's emails, newest first" and "the most recent
-- outbound one to reply to".
create index if not exists outreach_messages_prospect_date_idx
  on public.outreach_messages (prospect_id, message_date desc nulls last);
-- The daily cap counts non-test outbound rows in a calendar day; this is the index it walks.
create index if not exists outreach_messages_outbound_created_idx
  on public.outreach_messages (created_at desc)
  where direction = 'outbound' and is_test = false;

-- ── 🔴 RLS ON, ONE service_role POLICY, anon/authenticated REVOKED ─────────────────────────────────
-- The §52.2 pattern. Enabling RLS alone leaves the default grants in place, so the capability is still
-- reachable with the anon key; the revoke is the half that closes it. Every reader and writer of this
-- table is a server route using SUPABASE_SERVICE_ROLE_KEY, which bypasses RLS and is the only role
-- granted here. This table holds correspondence with named businesses; it is never client-readable.
alter table public.outreach_messages enable row level security;

drop policy if exists "service_role only" on public.outreach_messages;
create policy "service_role only" on public.outreach_messages
  for all to service_role using (true) with check (true);

revoke all on public.outreach_messages from anon, authenticated, public;

comment on table public.outreach_messages is
  'One row per outreach email, in or out. Written only by server routes using the service role.';

commit;

notify pgrst, 'reload schema';
